name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Replace with your .NET version

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ArgusService.sln

      # Build the project
      - name: Build the project
        run: dotnet build ArgusService.sln --configuration Release

      # Run tests
      - name: Run tests
        run: dotnet test ArgusService-UnitTest/ArgusService-UnitTest.csproj --configuration Release --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

      # Upload test results as artifacts
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: ./TestResults/test_results.trx
      
      # Parse test results
      - name: Parse test results
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/TestResults/*.trx'
